# Use a base image that supports multi-architecture
FROM --platform=linux/amd64 ubuntu:20.04

# Install necessary dependencies
RUN apt-get update -y && \
    apt-get install -y wget

# Download Bitcoin Core binaries
ARG BITCOIN_VERSION=0.21.0
ARG BITCOIN_DATA=/root/.bitcoin
RUN wget https://bitcoincore.org/bin/bitcoin-core-${BITCOIN_VERSION}/bitcoin-${BITCOIN_VERSION}-x86_64-linux-gnu.tar.gz -O /tmp/bitcoin.tar.gz && \
    tar -xzf /tmp/bitcoin.tar.gz -C /tmp && \
    install -m 0755 -o root -g root -t /usr/local/bin /tmp/bitcoin-${BITCOIN_VERSION}/bin/*

# Cleanup
RUN rm -rf /tmp/bitcoin* && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Create Bitcoin data directory
RUN mkdir -p ${BITCOIN_DATA}
VOLUME [${BITCOIN_DATA}]

# Copy the bitcoin.conf file from your project into the container
COPY bitcoin.conf /root/.bitcoin/bitcoin.conf

# Expose the port for JSON-RPC (testnet)
EXPOSE 18332

# Start bitcoind to run in testnet mode
ENTRYPOINT ["bitcoind", "-testnet"]
